---
kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: sriov-network-config-daemon
  namespace: kube-system
  annotations:
spec:
  selector:
    matchLabels:
      app: sriov-network-config-daemon
  template:
    metadata:
      annotations:
        target.workload.openshift.io/management: '{"effect": "PreferredDuringScheduling"}'
      labels:
        app: sriov-network-config-daemon
        component: network
        type: infra
        openshift.io/component: network
    spec:
      hostNetwork: true
      hostPID: true
      nodeSelector:
        kubernetes.io/os: linux
        feature.node.kubernetes.io/network-sriov.capable: "true"
      tolerations:
      - operator: Exists
      serviceAccountName: sriov-network-config-daemon
      priorityClassName: "system-node-critical"
      {{- if .ImagePullSecrets }}
      imagePullSecrets:
      {{- range .ImagePullSecrets }}
      - name: {{ . }}
      {{- end }}
      {{- end }}
      containers:
      - name: sriov-network-config-daemon
        image: {{.Image}}
        command:
          - sriov-network-config-daemon
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
        args:
          - "start"
        env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        volumeMounts:
        - name: host
          mountPath: /host
        lifecycle:
          preStop:
            exec:
              command: ["/bindata/scripts/clean-k8s-services.sh"]
      volumes:
      - name: host
        hostPath:
          path: /
